# Generated by Django 4.1.4 on 2023-03-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('img', models.ImageField(max_length=56400, upload_to='pics')),
                ('desc', models.TextField()),
            ],
        ),
    ]
