# Generated by Django 4.1.7 on 2023-03-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
